#!/usr/bin/env ruby

require 'open3'

require "#{File.dirname __FILE__}/install_scripts/colorize"

HOME = ENV['HOME']

if File.exist? "#{HOME}/.oh-my-zsh"
  STDERR.puts 'Oh-My-Zsh is already installed.'.green
  exit(1)
end

puts 'Downloading Oh-My-Zsh from GitHub (mfdorst/oh-my-zsh)...'.blue
omz_url = 'https://raw.github.com/mfdorst/oh-my-zsh/install-noreplace-zshrc/tools/install.sh'
omz_installer = `curl -fsSL #{omz_url}`
puts 'Done.'.blue

puts 'Running Oh-My-Zsh installer...'.blue
puts 'Using custom repo (mfodrst/oh-my-zsh)'.yellow

# Older versions of ruby don't support passing environment variables to +system+
# As a hack, we just prepend the script with some variable definitions
system %Q(
  ZSH=~/.oh-my-zsh
  REPO=mfdorst/oh-my-zsh
  BRANCH=install-noreplace-zshrc
  REPLACE_RC=no
  CHSH=no
  RUNZSH=no
  #{omz_installer}
)

puts 'Done.'.blue
