#!/usr/bin/env ruby

require "#{File.dirname __FILE__}/install_scripts/brew_setup"
require "#{File.dirname __FILE__}/install_scripts/platform"
require "#{File.dirname __FILE__}/install_scripts/symlink"
require "#{File.dirname __FILE__}/install_scripts/user_ask"

puts
puts "Ruby version: #{RUBY_VERSION}".red
puts

HOME = ENV['HOME']

if ARGV[0] == "-y"
  puts "Accepting all defaults.".yellow
  $accept_defaults = true
else
  $accept_defaults = false
end

Dir.entries("#{HOME}/.dotfiles/universal").reject{ |f| File.directory? f }.each do |f|
  symlink 'universal', f
end

case OS.which?
when :linux
  puts
  puts '--- Linux detected ---'.blue
  symlink 'platform_specific', '.zshrc.linux'
when :macos
  puts
  puts '--- macOS detected ---'.blue
  symlink 'platform_specific', '.zshrc.macos'
  symlink 'platform_specific', '.Brewfile'
  puts
  install_brew
end

puts
if File.exist? "#{HOME}/.oh-my-zsh"
  STDERR.puts 'Oh-My-Zsh is already installed.'.green
elsif user_ask :default_confirm, 'Would you like to install Oh-My-Zsh?'
  system "#{HOME}/.dotfiles/install-omz"
end

puts
if File.exist? "#{HOME}/.oh-my-zsh/custom/themes/spaceship-prompt"
  STDERR.puts 'Spaceship prompt is already installed.'.green
elsif user_ask :default_confirm, 'Would you like to install spaceship-prompt?'
  system "#{HOME}/.dotfiles/install-spaceship-prompt"
end

if (ENV['SHELL'] =~ /zsh/) == nil
  puts
  puts 'Run `chsh -s $(which zsh) && exec zsh` to switch to Zsh.'.yellow
end
