#!/usr/bin/env ruby

require 'open3'

require "#{File.dirname __FILE__}/install_scripts/colorize"

HOME = ENV['HOME']

if File.exist? "#{HOME}/.oh-my-zsh"
  STDERR.puts 'Oh-My-Zsh is already installed.'.green
  exit(1)
end

puts 'Downloading Oh-My-Zsh from GitHub (ohmyzsh/ohmyzsh)...'.blue
omz_url = 'https://github.com/ohmyzsh/ohmyzsh/blob/master/tools/install.sh'
omz_installer = `curl -fsSL #{omz_url}`
puts 'Done.'.blue

puts 'Running Oh-My-Zsh installer...'.blue

system '#{omz_installer} --unattended --keep-zshrc'

puts 'Done.'.blue
